USE sqlDatabase;

-- INSERTING A ROW IN CUSTOMER TABLE
INSERT INTO customer
VALUES (204, 'Lava', 'Kusha', 'Something', 'Germany', '9644434546')

SELECT * FROM customer

-- DISPLAY THE DETAILS FROM CUSTOMER TABLE WHO IS FROM COUNTRY GERMANY
SELECT * FROM customer
WHERE country LIKE 'GERMANY'

-- DISPLAY FULL NAME OF THE EMPLOYEE

SELECT firstName + ' ' + lastName AS fullName FROM customer

-- ADDING FAXNUMBER COLUMN

ALTER TABLE customer
ADD faxNumber varchar(15);

-- INSERING VALUES IN FAXNUMBER COLUMN IN CUSTOMER TABLE

UPDATE customer 
SET faxNumber = '+91-212-9342352'
WHERE id = 204;

-- DISPLAY THE CUSTOMER DETAILS WHO HAS FAX NUMBER

SELECT * FROM customer
WHERE faxNumber IS NOT NULL;

-- DISPLAY THE CUSTOMER DETAILS WHOSE NAME HOLDS SECOND LETTER AS A

SELECT * FROM customer
WHERE firstName LIKE '_a%'

-- SELECT ORDER DETAILS WHERE UNIT PRICE IS GREATER THAN 1000 AND LESS THAN 10000

SELECT * FROM orderr
WHERE id IN (SELECT orderId FROM orderItem WHERE unitPrice BETWEEN 1000 AND 10000)

-- ADDING SHIPPINGDATE COLUMN IN ORDERR TABLE

ALTER TABLE orderr
ADD shippingDate datetime;

-- UPDATING VALUES IN SHIPPINGDATE COLUMN IN ORDER TABLE

UPDATE orderr
SET shippingDate = '2023-01-03'
WHERE id = 303

-- DISPLAY ORDER DETAILS WHICH CONTAINS SHIPPING DATE AND ARRANGE THE ORDER BY DATE

SELECT * FROM orderr
WHERE shippingDate IS NOT NULL
ORDER BY shippingDate;

-- ADDING SHIPNAME COLUMN IN ORDERR TABLE

ALTER TABLE orderr
ADD shipName varchar(20);

SELECT * FROM orderr;
SELECT * FROM orderItem;
SELECT * FROM product;

-- ADDING VALUES IN SHIPNAME COLUMN IN ORDERR TABLE

UPDATE orderr
SET shipName = 'La corned abondance'
WHERE id = 301

-- PRINTING THE ORDERS SHIPPED BY SHIP NAME 'LA CORNED ABONDANCE' BETWEEN

SELECT * FROM orderr
WHERE shipName LIKE 'La corned abondance' AND (shippingDate BETWEEN '2023-01-01' AND '2023-01-15');
 
-- PRINTING THE AVERAGE QUANTITY ORDERED FOR EVERY PRODUCT

SELECT productId, AVG(quantity) AS average FROM orderItem
GROUP BY productId;

-- ADDING SHIPPING COMPANY COLUMN IN ORDERR TABLE

ALTER TABLE orderr
ADD shippingCompany varchar(20);

-- UPDATING VALUES FOR SHIPPINGCOMPANY COLUMN IN ORDERR TABLE

UPDATE orderr
SET shippingCompany = 'Amazon'
WHERE id = 303

-- PRINT ALL SHIPPING COMPANY NAME AND THE SHIP NAMES IF THEY ARE OPERATIONAL

SELECT shippingCompany, shipName FROM orderr WHERE shipName IS NOT NULL

-- ADDING CATEGORY COLUMN

ALTER TABLE product
ADD Category varchar(20);

-- UPDATING VALUES IN CATEGORY COLUMN

UPDATE product
SET category = 'portable'
WHERE id = 106;

-- ADDING DISCOUNT ATTRIBUTE IN PRODUCT TABLE

ALTER TABLE product
ADD discount int;

-- INSERTING VALUES FOR DISCOUNT ATTRIBUTE IN PRODUCT TABLE
UPDATE product
SET discount = 0
WHERE id = 106;


-- PRINTING THE BILL
SELECT productName, category, unitPrice - discount AS price FROM product;

-- PRINTING THE TOTAL PRICE AND SHIPPING COMPANY NAME OF ORDERS WHICH HAVE THE PRODUCTS SUPPLIED BY AMAZON IF THE PRICE IS > 50000

SELECT shippingCompany, totalAmount AS totalPrice FROM orderr
WHERE shippingCompany LIKE 'Amazon' AND totalAmount > 50000