USE sqlDatabase;

SELECT * FROM product
SELECT * FROM customer
SELECT * FROM orderr
SELECT * FROM orderItem

-- DISPLAYS THE ORDERS PLACED BY CUSTOMER WITH PHONE NUMBER 7852656548
SELECT * FROM orderr
WHERE customerId IN (SELECT id FROM customer WHERE phone = '7852656548')

-- FETCHING ALL THE PRODUCTS WHICH ARE AVAILABLE UNDER CATEGORY PORTABLE
SELECT * FROM product 
WHERE Category LIKE 'portable'

-- DISPLAYS THE ORDERS PLACED BY CUSTOMERS NOT IN GERMANY
SELECT * FROM orderr
WHERE customerId IN (SELECT id FROM customer WHERE country NOT LIKE 'Germany')

-- SELECTS ALL THE ORDER WHICH ARE PLACED FOR THE PRODUCT DESKTOP
SELECT * FROM orderr
WHERE id IN (SELECT orderId FROM orderItem WHERE productId IN 
			    (SELECT id FROM product WHERE productName LIKE 'Desktop'))


